#!/usr/bin/env bash
set -HCETeuxo pipefail
# remap \x08
echo '"\C-h": backward-kill-word' >| ${TMP_INPUTRC:=$(mktemp)}

# run test
INPUTRC=$TMP_INPUTRC bind -q '"\C-h"'

# cleanup
rm -fv $TMP_INPUTRC
