#!/usr/bin/env bash
set -HCETeuxo pipefail
# remap \x08
echo '"\C-h": backward-kill-word' >| ${TMP_INPUTRC:=$(mktemp)}

: test with override
INPUTRC=$TMP_INPUTRC bind -p | grep -E $'\C-h'

: test with devnull
INPUTRC=/dev/null bind -p | grep -E $'\C-h'

# cleanup
rm -fv $TMP_INPUTRC
